### PR TITLE
Closes #838 Better openuri exception reporting

### LINKED ISSUE #838: Better openuri exception reporting
https://github.com/openstax/tutor-server/blob/master/lib/openstax/cnx/v1.rb#L57

rescue `OpenURI::HTTPError` and reraise as some sort of Tutor HTTP error, including the URL being targeted so we can figure out what URL caused the error.  Append the rescued exception's message (e.g. "404 Not Found").  Exception email fragment that we get now is pasted below.

Check to see other places we could get this `OpenURI::HTTPError`, e.g. when we get Exercises?

Spec this by fetching made up URLs.

```
An OpenURI::HTTPError occurred in background at 2015-11-30 20:33:20 UTC :

  404 Not Found
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'

  -------------------------------
Backtrace:
-------------------------------

  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
  /home/osttutor/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in `open'
  /home/osttutor/src/tutor-7a13459/lib/openstax/cnx/v1.rb:57:in `fetch'
```

### PR DESCRIPTION
**Pull request by joemsak**

### CODE REVIEW

File: lib/openstax/cnx/v1.rb [hunk 1]
```diff
@@ -53,12 +53,26 @@ def self.url_for(id, options={})
...
   def self.fetch(id)
     url = url_for(id)
-    Rails.logger.debug { "Fetching #{url}" }
-    JSON.parse open(url_for(id), 'ACCEPT' => 'text/json').read
+
+    begin
+      Rails.logger.debug { "Fetching #{url}" }
+      JSON.parse open(url, 'ACCEPT' => 'text/json').read
+    rescue OpenURI::HTTPError => e
+      handle_not_found(e, url)
```
Comment (jpslav) [inline lib/openstax/cnx/v1.rb]: Can this always wrap the OpenURI errors?

```ruby
rescue OpenURI::HTTPError => e
  raise OpenStax::HTTPError, "#{e.message} for #{url}", e
end
```

With the causes being reported, this will give us the URL always added to top-level message in addition to whatever information is in the causing `e`.

Comment (joemsak) [inline lib/openstax/cnx/v1.rb]: For sure, thought you just wanted the 404

Comment (joemsak) [inline lib/openstax/cnx/v1.rb]: @jpslav done, thanks and good lookin out
